version: '3.8'
services:
  app:
    build: .
    volumes:
      - ..:/home/hyperultima/nest-tcp-server:cached
    networks:
      - nest-tcp-server-dev
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

networks:
  nest-tcp-server-dev:
